### ISSUE TITLE
[BUG:] UFC ADS1115/pot circuit.

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#1120]
## TODO
- [x] Fix analog inputs (pots)
  - [x] Fix Voltage Reference for ADCs (should be closer to 2V than 3.3V)
    - Add ADR5040ARTZ-REEL7 Analog Voltage Reference
  - [x] Move caps so they decouple pots (Wiper to GND) instead of an inadvertent RC tank circuit.
    ![image](https://github.com/user-attachments/assets/f1c39962-0b0d-4a7e-8ae2-1abb6a468b61)
    Video: https://github.com/user-attachments/assets/2912e9ba-d29c-4b39-8775-1ace75dd0ac2
  - [x] Add 1uF and .1uF decouple caps to all ADS1115 between VDD and GND.
- [x] Update silkscreen to Ver 6.3.1

### Optional Additions
- [ ] Add spare ADS1115 with pin header for future expansion.
- [x] Attempt to shoehorn DNP header for 5v, SDA, SCL and GND. (Optional)
- [x] Make 3x freed up I/O available via pin header.

Workaround for 6.3.0: Add a 6k resistor between the + side of each pot in the cable and remove the cap by each pot.

**Comment by jrsteensen** [comment]
Closed by #1171
