### ISSUE TITLE
"Analog" Standby Instrument Module

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#344]
Create a analog-instrument type Standby Instrument Module.

![unknown-30](https://user-images.githubusercontent.com/2449496/132005454-d1a2c161-0a55-4354-9c0d-5487ec892989.png)

### Airspeed Indicator (AS)

1. VID29 Microstepper
2. RGB Backlighting

### Altimeter (ALT)

1. VID60-02 360* Stepper w/ 0* Indication
2. 2X .5 White-on-black OLED (DFR0376, SEEED 30820004, or ER-OLEDM0.49)
3. RGB Backlighting
4. Encoder w/ Knob

### Vertical Velocity Indicator (VVI)

1. VID29 Microstepper
2. RGB Backlighting

### Standby Attitude Reference Indicator (SARI)

1. Pushbutton
2. Encoder with Pushbutton

### Radar Warning Receiver (RWR) Display

1. Encoder

### Display for SARI/RWR

1. ER-TFTV070A1-6

### Controller

1. Custom PCB for gauges, ABSIS Nano or Mega as required. 

### Other requirements

1. Utilize identical mount for module as existing 11.6" LCD solution
2. Add plug to inboard side of module since cutout in center pedestal will not be required.

**Comment by jrsteensen** [comment]
Evaluate adding 2X NeoPixel Diffused 5mm Through-Hole LED to each bezel at +/-30* for backlighting.
https://www.adafruit.com/product/1938 (Also available from digikey/mouser)

**Comment by jrsteensen** [comment]
Completed Altimeter, VVI, and Airspeed Gauges in commit 3727f9f. Behind the bezel, the altimeter and VVI are mechanically identical. These feature pinheader breakouts, neopixel edgelighting, and 2x small OLEDs for the altimeter tape spool mechanisms.

## TODO

- [ ] Clearance for 7" LCD top insertion.
- [ ] Hooks to position and retain LCD.
- [ ] ABSIS Mega Shield to control RWR & SARI controls, and ALT/AS/VVI Gauges.

**Comment by jrsteensen** [comment]
The above commit achieves design freeze candidate status for this. NOTE: This drove a change to the MFD Lower Support C - there is a .40 inch clearance cut to clear the 7" screen used for the SARI/RWR.
