### ISSUE TITLE
Create Drawing: OH3A2 - ASSY, EJECTION SEAT, SJU-17

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#559]
Create drawing OH3A2 - ASSY, EJECTION SEAT, SJU-17.

**Comment by jrsteensen** [comment]
SEAT Drawing at approximately 25% complete. All exploded views (39x) created.

**Comment by jrsteensen** [comment]
## TODO
- [ ] - [ ] -1200 VIEWS (RH SEAT BUCKET SKIN)
- [ ] RH SKIN FLAT PATTERN
- [ ] -1300 VIEWS (EJECTION HANDLE)
- [ ] -200 VIEWS (PARACHUTE CONTAINER)
- [ ] -300 VIEWS (SEAT RAILS)

**Comment by jrsteensen** [comment]
IN CHECK

[OH3A2-1 - ASSY, EJECTION SEAT, SJU-17_-_v26.pdf](https://github.com/jrsteensen/OpenHornet/files/11366616/OH3A2-1.-.ASSY.EJECTION.SEAT.SJU-17_-_v26.pdf)

**Comment by jrsteensen** [comment]
Added to RC Release Package and closed.

[OH3A2-1 - ASSY, EJECTION SEAT, SJU-17_-_v27.pdf](https://github.com/jrsteensen/OpenHornet/files/11378269/OH3A2-1.-.ASSY.EJECTION.SEAT.SJU-17_-_v27.pdf)
