### ISSUE TITLE
Set Beta1 Milestone on MCAD Model

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#963]
- [x] Top Level - Updated all to latest
- [x] UIP - Updated all to latest
- [x] LIP - Updated all to latest
- [x] CT - Updated all to latest
  - [x] Flight Stick top level needs to be re-jointed.
- [x] LC - Updated all to latest
- [x] RC - Updated all to latest

### v1.0.0-beta1-rc Milestone Set in Fusion
- [x] Top Level @ v1.0.0-beta1-rc milestone
- [x] UIP @ v1.0.0-beta1-rc milestone
- [x] LIP @ v1.0.0-beta1-rc milestone
- [x] CT @ v1.0.0-beta1-rc milestone
- [x] LC @ v1.0.0-beta1-rc milestone
- [x] RC @ v1.0.0-beta1-rc milestone

### v1.0.0-beta1 Milestone Set in Fusion
- [ ] Top Level @ v1.0.0-beta1 milestone
- [ ] UIP @ v1.0.0-beta1 milestone
- [ ] LIP @ v1.0.0-beta1 milestone
- [ ] CT @ v1.0.0-beta1 milestone
- [ ] LC @ v1.0.0-beta1 milestone
- [ ] RC @ v1.0.0-beta1 milestone

**Comment by jrsteensen** [comment]
All top level assemblies are set to `Initial Release - v0.2.0 (beta1)` milestone.
