### ISSUE TITLE
v0.2.0 (beta1) Release Checklist

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#965]
## Initial Preparation
- [x] Generate an issue named `<VERSION> Release Checklist`.
- [x] Copy the release checklist template from this page into the issue, and begin filling it out.
- [x] Ensure all needed changes are in the working milestone branch.

## Compiling the Release
- [x] Verify all changed drawings, MCAD and ECAD manufacturing files are in the `release` folder of the branch.
- [x] Set version milestone on Fusion models in Fusion repository, named same as release version.
- [x] Verify README.MD is updated in the `release` folder and all URLs are updated as appropriate.
- [x] ~~Verify CHANGELOG.MD is updated in the `release` folder.~~ Not required this release.
- [x] Verify LICENSE.MD is updated in the `release` folder.
- [x] Convert README.MD, ~~CHANGELOG.MD,~~ and LICENSE.MD to PDF and add to `release` folder.
- [x] ~~Generate 3D PDF from top level Fusion Model~~ Not feasible this release, and may not be in future.
- [x] ~~Add 3D PDF to `release` folder.~~ Not feasible this release, and may not be in future.
- [x] Add all Ultimate Supporters to release notes.
- [x] Merge branch to Master branch.
- [x] Manually create Release Package ZIP file to attach to the release.
- [x] ~~Generate #959 article on site (This release only.)~~ README detailed enough to not require.
- [x] Generate Release from Master branch, using release note template on this page, and attaching the release ZIP.

## Post-Release Actions
- [x] Generate article on website for new release with appropriate details.
- [x] Announce release on Discord **Announcements** channel.
- [x] Close this issue once checklist is completed.

**Comment by jrsteensen** [comment]
v0.2.0 released!
